left_hand:
  mono:
    device: 10
    width: 1600
    height: 1200
    fps: 30
  stereo:
    device: 8
    width: 3840
    height: 1080
    fps: 30
    calibration_file: stereo_calibration/left/stereo_calibration_left.json
    calibration:
      left_camera_matrix:
      - - 1000.0611440256292
        - 0.0
        - 988.0145793823278
      - - 0.0
        - 1000.4085089133481
        - 606.5268322315351
      - - 0.0
        - 0.0
        - 1.0
      left_distortion:
      - - 0.07238347285625159
        - -0.13984274658860046
        - 0.0010139502412446488
        - -0.0002187548714614688
        - 0.05796166890242859
      right_camera_matrix:
      - - 1000.7616145236483
        - 0.0
        - 963.4369281421789
      - - 0.0
        - 1001.1807534758645
        - 512.1944671394912
      - - 0.0
        - 0.0
        - 1.0
      right_distortion:
      - - 0.06405550904033938
        - -0.09273112223197048
        - 0.0004624409059099165
        - -0.0007933681752384865
        - 0.004991996544228194
      rotation:
      - - 0.999998691317952
        - -0.0008403950289213936
        - 0.001382424890778654
      - - 0.0008482145426126056
        - 0.9999835909176892
        - -0.00566554740984692
      - - -0.0013776409085754719
        - 0.005666712588343163
        - 0.9999829950924006
      translation:
      - - -65.02856409583048
      - - -0.42088212396038915
      - - 0.0173519231449318
      rectify_rotation_left:
      - - 0.9999835686456392
        - 0.005630133942353721
        - 0.001078902462459029
      - - -0.005627052355760397
        - 0.9999801400137951
        - -0.002838284653836183
      - - -0.0010948609582386462
        - 0.00283216697633224
        - 0.9999953900442243
      rectify_rotation_right:
      - - 0.9999790199501362
        - 0.006472129589270275
        - -0.0002668298053629697
      - - -0.00647134704577891
        - 0.9999750387459972
        - 0.002836115715965581
      - - 0.00028517885340030466
        - -0.0028343294658437815
        - 0.9999959426165191
      projection_left:
      - - 1133.2159163344318
        - 0.0
        - 973.9336318969727
        - 0.0
      - - 0.0
        - 1133.2159163344318
        - 556.5132064819336
        - 0.0
      - - 0.0
        - 0.0
        - 1.0
        - 0.0
      projection_right:
      - - 1133.2159163344318
        - 0.0
        - 973.9336318969727
        - -73692.94993153306
      - - 0.0
        - 1133.2159163344318
        - 556.5132064819336
        - 0.0
      - - 0.0
        - 0.0
        - 1.0
        - 0.0
      disparity_to_depth:
      - - 1.0
        - 0.0
        - 0.0
        - -973.9336318969727
      - - 0.0
        - 1.0
        - 0.0
        - -556.5132064819336
      - - 0.0
        - 0.0
        - 0.0
        - 1133.2159163344318
      - - 0.0
        - 0.0
        - 0.015377534993337686
        - -0.0
      baseline_mm: 1625.748210674288
      image_size:
      - 1920
      - 1080
      reprojection_error: 0.12582156628406602
      calibration_date: '2026-01-06T13:45:13.672724'
      calibrated: true
  encoder:
    port: /dev/ttyUSB1
    baudrate: 115200
    calibration:
      angle_zero: 120.443115234375
      calibrated: true
right_hand:
  mono:
    device: 6
    width: 1600
    height: 1200
    fps: 30
  stereo:
    device: 4
    width: 3840
    height: 1080
    fps: 30
    calibration_file: stereo_calibration/right/stereo_calibration_right.json
    calibration:
      left_camera_matrix:
      - - 1009.4227863286723
        - 0.0
        - 975.6984855742896
      - - 0.0
        - 1009.1132601953515
        - 565.8371193779603
      - - 0.0
        - 0.0
        - 1.0
      left_distortion:
      - - 0.03557719030540865
        - 0.020183248401438144
        - -0.000795390849206791
        - 0.0004709884406446608
        - -0.13636658279411726
      right_camera_matrix:
      - - 1004.5685078136705
        - 0.0
        - 976.1629826038155
      - - 0.0
        - 1004.2135358854549
        - 527.057202666254
      - - 0.0
        - 0.0
        - 1.0
      right_distortion:
      - - 0.04916766186423046
        - -0.06381266948547523
        - 0.0005560190353098875
        - 0.0005268604155511556
        - -0.01189178299870985
      rotation:
      - - 0.9999619017340422
        - -3.8875857168290824e-05
        - -0.008728892776603955
      - - 4.623961202595772e-05
        - 0.9999996432634136
        - 0.0008434067487680777
      - - 0.008728856874528243
        - -0.0008437782370488593
        - 0.9999615468086513
      translation:
      - - -65.6006576328522
      - - 0.225140343388965
      - - -1.2753858240661755
      rectify_rotation_left:
      - - 0.9999365994984902
        - -0.0034865827153857127
        - 0.010707040878069098
      - - 0.003482148798062679
        - 0.9999938436747133
        - 0.00043272672800917977
      - - -0.010708483699572956
        - -0.00039541578339323107
        - 0.9999425843633295
      rectify_rotation_right:
      - - 0.9998051785800942
        - -0.0034313144006469665
        - 0.019437874521399882
      - - 0.003439363291185516
        - 0.9999940129181752
        - -0.00038066777571416164
      - - -0.019436451954433956
        - 0.0004474475255651576
        - 0.9998109942014715
      projection_left:
      - - 1069.5179067938523
        - 0.0
        - 961.6842193603516
        - 0.0
      - - 0.0
        - 1069.5179067938523
        - 543.662712097168
        - 0.0
      - - 0.0
        - 0.0
        - 1.0
        - 0.0
      projection_right:
      - - 1069.5179067938523
        - 0.0
        - 961.6842193603516
        - -70174.74958014298
      - - 0.0
        - 1069.5179067938523
        - 543.662712097168
        - 0.0
      - - 0.0
        - 0.0
        - 1.0
        - 0.0
      disparity_to_depth:
      - - 1.0
        - 0.0
        - 0.0
        - -961.6842193603516
      - - 0.0
        - 1.0
        - 0.0
        - -543.662712097168
      - - 0.0
        - 0.0
        - 0.0
        - 1069.5179067938523
      - - 0.0
        - 0.0
        - 0.015240779813149329
        - -0.0
      baseline_mm: 1640.3360134125605
      image_size:
      - 1920
      - 1080
      reprojection_error: 0.21743514662581606
      calibration_date: '2026-01-06T13:45:21.132252'
      calibrated: true
  encoder:
    port: /dev/ttyUSB0
    baudrate: 115200
    calibration:
      angle_zero: 60.479736328125
      calibrated: true
